### Why we vectorized version than using explicit for loops in the code? 

#### Does it have a effect on time taken by the code

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time 

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()


print(c)
print("For loop:" + str(1000*(toc-tic))+"ms")

249715.68311335758
Vectorized version:24.856090545654297ms
249715.68311334337
For loop:511.26813888549805ms


The non-vectorize version took something like 300 times longer than the vectorize version. With this example you see that if only you remember to vectorize your code, your code actually runs over 300 times faster.

=====================================

### Broadcasting in python

In [3]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0) #sum vertically 
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100*(A/cal.reshape(1,4)) 
#reshape(1,4) means outer dimansion will have 01 array which will have 04 elements of its own 
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


=====================================

### A note on python, numpy vectors

In [6]:
import numpy as np

a = np.random.randn(5)
#created a data structure with shape(5,)
#rank one array

In [7]:
print(a)

[-0.83677319  0.50970444 -0.3993047  -0.43610008  0.14996609]


In [8]:
print(a.shape) #rank one array in python
# neither a row vector nor a column vector
#thats why non intuitive
#advised not to use it 
#always use (5,1) or (1,5) type of array 

(5,)


In [9]:
print(a.T) 
#this shows that a and a transpose end up looking the same 

[-0.83677319  0.50970444 -0.3993047  -0.43610008  0.14996609]


In [10]:
print(np.dot(a,a.T))

1.3321053248028978


In [11]:
a = np.random.randn(5,1)
print(a)

[[ 0.08989067]
 [ 1.74118737]
 [-0.28143672]
 [ 0.3009454 ]
 [-1.52656571]]


In [12]:
print(a.T)

[[ 0.08989067  1.74118737 -0.28143672  0.3009454  -1.52656571]]


there is difference between this a transpose and the previous one that this one has two square brackets 

In [13]:
print(np.dot(a,a.T))

[[ 0.00808033  0.15651649 -0.02529853  0.02705218 -0.13722401]
 [ 0.15651649  3.03173345 -0.49003406  0.52400233 -2.65803693]
 [-0.02529853 -0.49003406  0.07920663 -0.08469709  0.42963164]
 [ 0.02705218  0.52400233 -0.08469709  0.09056813 -0.45941292]
 [-0.13722401 -2.65803693  0.42963164 -0.45941292  2.33040286]]


In [14]:
assert(a.shape==(5,1))
#to be entirely sure that i have (5,1) vecotr, a column vector 
#to check that we are actually using this shape and not rank one array 

In [15]:
print(a.shape)

(5, 1)


In [16]:
#and suppose we are using rank one array and we want to change it then:
a = a. reshape((1,5))

In [17]:
print(a.shape)

(1, 5)


## Assignment

In [18]:
a=np.array([[2,1],[1,3]])
x = np.dot(a,a)
print(x)

[[ 5  5]
 [ 5 10]]


In [19]:
a=np.random.randn(3,3)
b = np.random.randn(3, 1)
b=np.random.randn(3,1)
c = a*b
print(a)
print( )
print(b)
print( )
print(c)

[[ 1.92114793 -1.08947629  0.30869957]
 [-0.63566524  0.44937907 -2.0689927 ]
 [ 0.31131315  1.30761511 -0.37763945]]

[[-1.30004684]
 [ 0.02245874]
 [ 0.56510978]]

[[-2.4975823   1.41637021 -0.4013239 ]
 [-0.01427624  0.01009249 -0.04646697]
 [ 0.17592611  0.73894609 -0.21340774]]


In [20]:
a=np.random.randn(4,3)
b = np.random.randn(3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [21]:
a=np.random.randn(1,3) 
b = np.random.randn(3, 3)
c = a*b
print(c.shape)

(3, 3)


In [22]:
a=np.array([[2,1],[1,3]])
print(np.dot(a,a))

[[ 5  5]
 [ 5 10]]


In [23]:
a.shape=(4,3)
b.shape=(4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[j][i] + b[j]

ValueError: cannot reshape array of size 4 into shape (4,3)

In [24]:
a=np.random.randn(3,4) # a.shape = (3, 4)a.shape=(3,4)

b = np.random.randn(1, 4)
c = a + b
print(c.shape)

(3, 4)


In [25]:
a=np.random.randn(1,3)

b = np.random.randn(3, 3)
c = a*b
print(c.shape)

(3, 3)


In [26]:
a=np.array([[2,1],[1,3]])
print(a*a)

[[4 1]
 [1 9]]


In [27]:
a=np.random.randn(3,3)
b = np.random.randn(3,3)
a.shape=(3,3)
b.shape = (3, 3)
c = a**2 + b.T**2
print(c)

print( )
for i in range(3):
     for j in range(3):
            c[i][j] = a[i][j]**2 + b[j][i]**2
print(c)

[[1.13341149 1.17813259 1.50873036]
 [0.34979648 0.1218841  0.0085251 ]
 [1.92367803 1.38174589 0.69361644]]

[[1.13341149 1.17813259 1.50873036]
 [0.34979648 0.1218841  0.0085251 ]
 [1.92367803 1.38174589 0.69361644]]
